In [3]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("C:\\Users\\SAKSHAM\\Downloads\\customer_shopping_behavior.csv")
print(df.head())

   Customer ID  Age Gender Item Purchased  Category  Purchase Amount (USD)  \
0            1   55   Male         Blouse  Clothing                     53
1            2   19   Male        Sweater  Clothing                     64
2            3   50   Male          Jeans  Clothing                     73
3            4   21   Male        Sandals  Footwear                     90
4            5   45   Male         Blouse  Clothing                     49

        Location Size      Color  Season  Review Rating Subscription Status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes
1          Maine    L     Maroon  Winter            3.1                 Yes
2  Massachusetts    S     Maroon  Spring            3.1                 Yes
3   Rhode Island    M     Maroon  Spring            3.5                 Yes
4         Oregon    M  Turquoise  Spring            2.7                 Yes

   Shipping Type Discount Applied Promo Code Used  Previous Purchases  \
0        Express              Yes             Yes                  14
1        Express              Yes             Yes                   2
2  Free Shipping              Yes             Yes                  23
3   Next Day Air              Yes             Yes                  49
4  Free Shipping              Yes             Yes                  31

  Payment Method Frequency of Purchases
0          Venmo            Fortnightly
1           Cash            Fortnightly
2    Credit Card                 Weekly
3         PayPal                 Weekly
4         PayPal               Annually

In [5]:
df.columns.tolist()

['Customer ID',
 'Age',
 'Gender',
 'Item Purchased',
 'Category',
 'Purchase Amount (USD)',
 'Location',
 'Size',
 'Color',
 'Season',
 'Review Rating',
 'Subscription Status',
 'Shipping Type',
 'Discount Applied',
 'Promo Code Used',
 'Previous Purchases',
 'Payment Method',
 'Frequency of Purchases']

In [6]:
print(df.head())

   Customer ID  Age Gender Item Purchased  Category  Purchase Amount (USD)  \
0            1   55   Male         Blouse  Clothing                     53
1            2   19   Male        Sweater  Clothing                     64
2            3   50   Male          Jeans  Clothing                     73
3            4   21   Male        Sandals  Footwear                     90
4            5   45   Male         Blouse  Clothing                     49

        Location Size      Color  Season  Review Rating Subscription Status  \
0       Kentucky    L       Gray  Winter            3.1                 Yes
1          Maine    L     Maroon  Winter            3.1                 Yes
2  Massachusetts    S     Maroon  Spring            3.1                 Yes
3   Rhode Island    M     Maroon  Spring            3.5                 Yes
4         Oregon    M  Turquoise  Spring            2.7                 Yes

   Shipping Type Discount Applied Promo Code Used  Previous Purchases  \
0        Express              Yes             Yes                  14
1        Express              Yes             Yes                   2
2  Free Shipping              Yes             Yes                  23
3   Next Day Air              Yes             Yes                  49
4  Free Shipping              Yes             Yes                  31

  Payment Method Frequency of Purchases
0          Venmo            Fortnightly
1           Cash            Fortnightly
2    Credit Card                 Weekly
3         PayPal                 Weekly
4         PayPal               Annually

In [7]:
df.count('columns')

0       18
1       18
2       18
3       18
4       18
        ..
3895    18
3896    18
3897    18
3898    18
3899    18
Length: 3900, dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [9]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [10]:
df.columns.tolist()

['customer_id',
 'age',
 'gender',
 'item_purchased',
 'category',
 'purchase_amount_(usd)',
 'location',
 'size',
 'color',
 'season',
 'review_rating',
 'subscription_status',
 'shipping_type',
 'discount_applied',
 'promo_code_used',
 'previous_purchases',
 'payment_method',
 'frequency_of_purchases']

In [11]:
df.info(
)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             3900 non-null   int64
 1   age                     3900 non-null   int64
 2   gender                  3900 non-null   object
 3   item_purchased          3900 non-null   object
 4   category                3900 non-null   object
 5   purchase_amount_(usd)   3900 non-null   int64
 6   location                3900 non-null   object
 7   size                    3900 non-null   object
 8   color                   3900 non-null   object
 9   season                  3900 non-null   object
 10  review_rating           3863 non-null   float64
 11  subscription_status     3900 non-null   object
 12  shipping_type           3900 non-null   object
 13  discount_applied        3900 non-null   object
 14  promo_code_used         3900 non-null   object
 15  previous_purchases      3900 non-null   int64
 16  payment_method          3900 non-null   object
 17  frequency_of_purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [12]:
df["review_rating"].isnull().sum()

np.int64(37)

In [13]:
df["review_rating"]=df["review_rating"].fillna(df["review_rating"].median())

In [14]:
df["review_rating"].isnull().sum()

np.int64(0)

In [15]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             3900 non-null   int64
 1   age                     3900 non-null   int64
 2   gender                  3900 non-null   object
 3   item_purchased          3900 non-null   object
 4   category                3900 non-null   object
 5   purchase_amount_(usd)   3900 non-null   int64
 6   location                3900 non-null   object
 7   size                    3900 non-null   object
 8   color                   3900 non-null   object
 9   season                  3900 non-null   object
 10  review_rating           3900 non-null   float64
 11  subscription_status     3900 non-null   object
 12  shipping_type           3900 non-null   object
 13  discount_applied        3900 non-null   object
 14  promo_code_used         3900 non-null   object
 15  previous_purchases      3900 non-null   int64
 16  payment_method          3900 non-null   object
 17  frequency_of_purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

,customer_id,age,purchase_amount_(usd),review_rating,previous_purchases
count,3900.000000,3900.000000,3900.000000,3900.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750538,25.351538
std,1125.977353,15.207589,23.685392,0.713589,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [16]:
df.columns=df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [17]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [18]:
(df['discount_applied']==df['promo_code_used']).all()
df[['discount_applied','promo_code_used']].head()

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer_id             3900 non-null   int64
 1   age                     3900 non-null   int64
 2   gender                  3900 non-null   object
 3   item_purchased          3900 non-null   object
 4   category                3900 non-null   object
 5   purchase_amount_(usd)   3900 non-null   int64
 6   location                3900 non-null   object
 7   size                    3900 non-null   object
 8   color                   3900 non-null   object
 9   season                  3900 non-null   object
 10  review_rating           3900 non-null   float64
 11  subscription_status     3900 non-null   object
 12  shipping_type           3900 non-null   object
 13  discount_applied        3900 non-null   object
 14  promo_code_used         3900 non-null   object
 15  previous_purchases      3900 non-null   int64
 16  payment_method          3900 non-null   object
 17  frequency_of_purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [20]:
labels = ['child', 'teenager', 'adult', 'senior']
df['age_group'] = pd.qcut(df['age'],q=4,labels=labels)

In [21]:
df['age_group'].value_counts()

age_group
child       1028
adult        986
senior       944
teenager     942
Name: count, dtype: int64

In [22]:
df['frequency_of_purchases'].value_counts()

frequency_of_purchases
Every 3 Months    584
Annually          572
Quarterly         563
Monthly           553
Bi-Weekly         547
Fortnightly       542
Weekly            539
Name: count, dtype: int64

In [23]:
frequency_mapping = {
'Every 3 Months'  :  90,
'Annually'      :  365,
'Quarterly'      :   90,
'Monthly'       :    30,
'Bi-Weekly'     :    14,
'Fortnightly'    :   14,
'Weekly'   : 7
}

df['purchaase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [24]:
df.info(['frequency_of_purchases','purchase_frequency_days'])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               3900 non-null   int64
 1   age                       3900 non-null   int64
 2   gender                    3900 non-null   object
 3   item_purchased            3900 non-null   object
 4   category                  3900 non-null   object
 5   purchase_amount_(usd)     3900 non-null   int64
 6   location                  3900 non-null   object
 7   size                      3900 non-null   object
 8   color                     3900 non-null   object
 9   season                    3900 non-null   object
 10  review_rating             3900 non-null   float64
 11  subscription_status       3900 non-null   object
 12  shipping_type             3900 non-null   object
 13  discount_applied          3900 non-null   object
 14  promo_code_used           3900 non-null   object
 15  previous_purchases        3900 non-null   int64
 16  payment_method            3900 non-null   object
 17  frequency_of_purchases    3900 non-null   object
 18  age_group                 3900 non-null   category
 19  purchaase_frequency_days  3900 non-null   int64
dtypes: category(1), float64(1), int64(5), object(13)
memory usage: 583.0+ KB

In [25]:
df=df.rename(columns = {'purchase_amount_(usd)':'purchase_amount'})

In [26]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases', 'age_group',
       'purchaase_frequency_days'],
      dtype='object')

In [27]:
pip install pymysql sqlalchemy

Requirement already satisfied: pymysql in c:\users\saksham\appdata\local\programs\python\python314\lib\site-packages (1.1.2)
Requirement already satisfied: sqlalchemy in c:\users\saksham\appdata\local\programs\python\python314\lib\site-packages (2.0.49)
Requirement already satisfied: greenlet>=1 in c:\users\saksham\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\saksham\appdata\local\programs\python\python314\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [28]:
from sqlalchemy import create_engine
username = 'root'
password = 'saksham294'
host = 'localhost'
port = '3306'
database = 'customer'

engine = create_engine(f'mysql+pymysql://{username}:{password}@{host}:{port}/{database}')

table_name = 'customer_shopping_behavior'
df.to_sql(table_name, con=engine, if_exists='replace', index=False)
pd.read_sql(f'SELECT * FROM {table_name} limit 5;', con=engine)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group,purchaase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,adult,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,child,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,adult,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,child,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,adult,365